# Generated by Django 5.1.6 on 2025-02-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="comment",
            new_name="text",
        ),
        migrations.AlterField(
            model_name="play",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
