# Generated by Django 5.1.6 on 2025-02-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0003_rename_comment_review_text_alter_play_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="plays/"),
        ),
    ]
