# Generated by Django 5.1.6 on 2025-03-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0006_alter_reservation_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="play",
            name="rating",
        ),
    ]
